### ISSUE TITLE
Windows release doesn't work

### ISSUE THREAD

**Issue by kamalist** [toyknight/project_aeii#10]
After pressing Launch button the game throws NullPointerException.

Exception in thread "LWJGL Application" java.lang.NullPointerException
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.createDisplayPixelFormat(LwjglGraphics.java:321)
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setupDisplay(LwjglGraphics.java:215)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:142)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)

Tried with the same error both in Windows XP and Windows 7, Java 1.6-1.7

**Comment by toyknight** [comment]
![123](https://cloud.githubusercontent.com/assets/4530116/17086933/72de68ae-51cc-11e6-8b22-4c86664dbc52.png)
Well the LwjglGraphics.java line 321 says `OpenGL is not supported by the video driver`. Maybe you should check your video card driver.

**Comment by kamalist** [comment]
Yes,  I am using VirtualBox for testing and by default video card was off. After I turn acceleration on  the game begins to work but the image is noticeably blinking. Maybe it is  because of low amount of video memory,  I don't know. Also the game declined to use JRE 1.6

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.UnsupportedClassVersionError: org/json/JSONException : Unsupported major.minor version 51.0
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:131)
Caused by: java.lang.UnsupportedClassVersionError: org/json/JSONException : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$000(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClassInternal(Unknown Source)
	at net.toyknight.aeii.manager.GameManager.<init>(GameManager.java:70)
	at net.toyknight.aeii.GameContext.initialize(GameContext.java:125)
	at net.toyknight.aeii.screen.LoadingScreen.render(LoadingScreen.java:49)
	at com.badlogic.gdx.Game.render(Game.java:46)
	at net.toyknight.aeii.GameContext.render(GameContext.java:422)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:223)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)

It supports only JRE 1.7. Don't know if you will count it as a bug, but it is in there

**Comment by toyknight** [comment]
Hmm, it seems the JSON library in desktop version does not support JRE 1.6. So just use the JRE I embedded in the game package it will be fine. BTW if you are not using windows you can install JRE for your system manually and run the AEII.jar file in the windows version package.
